# Generated by Django 6.0.4 on 2026-09-20 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0002_initial"),
        ("purchases", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasesinvoice",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="purchasesinvoice",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last updated this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="purchasesinvoice",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="inventory.warehouse",
            ),
        ),
        migrations.AddField(
            model_name="purchasesinvoiceitem",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="purchases.purchasesinvoice",
            ),
        ),
        migrations.AddField(
            model_name="purchasesinvoiceitem",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchases",
                to="inventory.variant",
            ),
        ),
        migrations.AddField(
            model_name="purchasesorder",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="purchasesorder",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last updated this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="purchasesinvoice",
            name="order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice",
                to="purchases.purchasesorder",
            ),
        ),
        migrations.AddField(
            model_name="purchasesorderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="purchases.purchasesorder",
            ),
        ),
        migrations.AddField(
            model_name="purchasesorderitem",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchases_items",
                to="inventory.variant",
            ),
        ),
        migrations.AddField(
            model_name="purchasespayment",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="purchases.purchasesinvoice",
            ),
        ),
        migrations.AddField(
            model_name="purchasespayment",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="purchases.purchasesorder",
            ),
        ),
        migrations.AddField(
            model_name="purchasespayment",
            name="processed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last updated this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="purchasespayment",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="purchases.supplier",
            ),
        ),
        migrations.AddField(
            model_name="purchasesorder",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="purchases.supplier",
            ),
        ),
        migrations.AddField(
            model_name="purchasesinvoice",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="purchases.supplier",
            ),
        ),
        migrations.AddIndex(
            model_name="purchasesinvoiceitem",
            index=models.Index(
                fields=["invoice"], name="purchases_p_invoice_a7a55f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchasesinvoiceitem",
            index=models.Index(
                fields=["variant"], name="purchases_p_variant_d38363_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchasesinvoiceitem",
            index=models.Index(
                fields=["expiry_date"], name="purchases_p_expiry__96283f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchasesinvoiceitem",
            constraint=models.UniqueConstraint(
                fields=("invoice", "variant"), name="unique_purchases_invoice_variant"
            ),
        ),
        migrations.AddIndex(
            model_name="purchasesorderitem",
            index=models.Index(fields=["order"], name="purchases_p_order_i_55c280_idx"),
        ),
        migrations.AddIndex(
            model_name="purchasesorderitem",
            index=models.Index(
                fields=["variant"], name="purchases_p_variant_a4791e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchasesorderitem",
            constraint=models.UniqueConstraint(
                fields=("order", "variant"), name="unique_purchases_order_variant"
            ),
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(fields=["code"], name="purchases_s_code_ed3223_idx"),
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(fields=["email"], name="purchases_s_email_1cee4a_idx"),
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(fields=["phone"], name="purchases_s_phone_9eb47a_idx"),
        ),
        migrations.AddIndex(
            model_name="purchasespayment",
            index=models.Index(
                fields=["payment_id"], name="purchases_p_payment_fd34b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchasespayment",
            index=models.Index(
                fields=["transaction_id"], name="purchases_p_transac_3556ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchasespayment",
            index=models.Index(
                fields=["status", "payment_date"], name="purchases_p_status_ddb49e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchasespayment",
            index=models.Index(
                fields=["invoice", "status"], name="purchases_p_invoice_557854_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchasesorder",
            index=models.Index(fields=["code"], name="purchases_p_code_8e21aa_idx"),
        ),
        migrations.AddIndex(
            model_name="purchasesorder",
            index=models.Index(fields=["status"], name="purchases_p_status_3edaa8_idx"),
        ),
        migrations.AddIndex(
            model_name="purchasesorder",
            index=models.Index(
                fields=["supplier", "order_date"], name="purchases_p_supplie_0439fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchasesinvoice",
            index=models.Index(fields=["code"], name="purchases_p_code_bddb24_idx"),
        ),
        migrations.AddIndex(
            model_name="purchasesinvoice",
            index=models.Index(fields=["status"], name="purchases_p_status_557349_idx"),
        ),
        migrations.AddIndex(
            model_name="purchasesinvoice",
            index=models.Index(
                fields=["supplier"], name="purchases_p_supplie_02d4fb_idx"
            ),
        ),
    ]
