"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from decouple import config


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", cast=bool, default=False)

ALLOWED_HOSTS = config(
    "ALLOWED_HOSTS",
    cast=lambda v: [s.strip() for s in v.split(",")],
    default="127.0.0.1,localhost"
)


# =========================================================
# APPLICATIONS
# =========================================================
DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

THIRD_PARTY_APPS = [
    "django_filters", 
    "rest_framework", 
    "rest_framework_simplejwt", 
    "rest_framework_simplejwt.token_blacklist", 
    "drf_spectacular", 
    "django_scalar", 
    "corsheaders", 
]

LOCAL_APPS = [
    "apps.inventory",
    "apps.sales",
    "apps.purchases",
    "apps.users",
    "apps.accounting",
]

INSTALLED_APPS = (
    DJANGO_APPS
    + THIRD_PARTY_APPS
    + LOCAL_APPS
)


# =========================================================
# MIDDLEWARE
# =========================================================
MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# =========================================================
# TEMPLATES
# =========================================================
TEMPLATES = [
    {
        "BACKEND"  : "django.template.backends.django.DjangoTemplates",
        "DIRS"     : [BASE_DIR / "templates"],
        "APP_DIRS" : True,
        "OPTIONS"  : {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# =========================================================
# URLS / WSGI
# =========================================================
ROOT_URLCONF = "config.urls"

WSGI_APPLICATION = "config.wsgi.application"

ASGI_APPLICATION = "core.asgi.application"


# =========================================================
# DTABASES
# =========================================================
DATABASES = {
    "default": {
        "ENGINE"  : "django.db.backends.postgresql",
        "NAME"    : config("DB_NAME"),
        "USER"    : config("DB_USER"),
        "PASSWORD": config("DB_PASSWORD"),
        "HOST"    : config("DB_HOST", default="127.0.0.1"),
        "PORT"    : config("DB_PORT", default="5432"),
    }
}


# =========================================================
# AUTHENTICATION
# =========================================================
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# =========================================================
# INTERNATIONALIZATION
# =========================================================
LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# =========================================================
# STATIC / MEDIA
# =========================================================
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"


# =========================================================
# DEFAULT PRIMARY KEY
# =========================================================
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# =========================================================
# CUSTOM USER MODEL
# =========================================================
AUTH_USER_MODEL = "users.User"


# =========================================================
# DJANGO REST FRAMEWORK
# =========================================================
REST_FRAMEWORK = {

    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),

    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),

    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ),

    "DEFAULT_SCHEMA_CLASS": (
        "drf_spectacular.openapi.AutoSchema"
    ),

    "DEFAULT_PAGINATION_CLASS":
        "common.pagination.StandardResultsPyQtPagination",

    "PAGE_SIZE": 30,

    "DEFAULT_FILTER_BACKENDS": (
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ),

    "EXCEPTION_HANDLER":
        "common.exceptions.handlers.custom_exception_handler",

    'DATETIME_FORMAT': '%Y-%m-%dT%H:%M:%S',
}


# =========================================================
# SIMPLE JWT
# =========================================================
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),

    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,

    "ALGORITHM": "HS256",

    "SIGNING_KEY": config("JWT_SECRET_KEY"),

    "AUTH_HEADER_TYPES": ("Bearer",),

    "AUTH_TOKEN_CLASSES": (
        "rest_framework_simplejwt.tokens.AccessToken",
    ),
}


# =========================================================
# CORS
# =========================================================
# Desktop PyQt client talks to the API directly; keep this tight.
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]


# =========================================================
# LOGGING
# =========================================================
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    "formatters": {
        "standard": {
            "format": "[{levelname}] {asctime} {module} : {message}",
            "style": "{",
        },
    },

    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
    },

    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}


# =========================================================
# SECURITY HEADERS (PRODUCTION)
# =========================================================
#if not DEBUG:
#    SECURE_BROWSER_XSS_FILTER = True
#    X_FRAME_OPTIONS = "DENY"
#    SECURE_CONTENT_TYPE_NOSNIFF = True
#
#    SESSION_COOKIE_SECURE = True
#    CSRF_COOKIE_SECURE = True
#
#    SECURE_SSL_REDIRECT = True


# =========================================================
# SPECTACULAR SETTINGS
# =========================================================
SPECTACULAR_SETTINGS = {
    "TITLE": "STORICA API",
    "DESCRIPTION": "STORICA Backend API Documentation",
    "VERSION": "1.0.0",

    "SERVE_INCLUDE_SCHEMA": False,

    # Better organization
    "COMPONENT_SPLIT_REQUEST": True,

    # Swagger UI settings
    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "persistAuthorization": True,
        "displayOperationId": True,
    },

    # Dark mode-ish modern UI
    "SWAGGER_UI_DIST": "SIDECAR",
    "SWAGGER_UI_FAVICON_HREF": "SIDECAR",

    "REDOC_DIST": "SIDECAR",

    # SECURITY
    "SECURITY": [
        {
            "BearerAuth": [],
        }
    ],

    "COMPONENTS": {
        "securitySchemes": {
            "BearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
            }
        }
    },

    # ENUM NAME
    "ENUM_NAME_OVERRIDES": {
        "WarehouseStatus": (
            "apps.inventory.models.WarehouseStatus"
        ), 
        "BatchStatus": (
            "apps.inventory.models.BatchStatus"
        ), 
        "MovementStatus": (
            "apps.inventory.models.MovementStatus"
        ), 
        "StockMovementType": (
            "apps.inventory.models.StockMovementType"
        ), 
        "UnitChoices": (
            "apps.inventory.models.UnitChoices"
        ), 

        "OrderStatus": (
            "apps.sales.models.OrderStatus"
        ), 
        "InvoiceStatus": (
            "apps.sales.models.InvoiceStatus"
        ), 
        "PaymentStatus": (
            "apps.sales.models.PaymentStatus"
        ), 
    }
}



