# Generated by Django 6.0.4 on 2026-09-20 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentry",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="journal_entries_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="reversed_entry",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, this entry reverses the linked original.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reversals",
                to="accounting.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="journalline",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="journal_lines",
                to="accounting.account",
            ),
        ),
        migrations.AddField(
            model_name="journalline",
            name="entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="accounting.journalentry",
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["account_type", "is_active"],
                name="accounting__account_e6bebd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["source_type", "source_id"],
                name="accounting__source__3d844c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["entry_date"], name="accounting__entry_d_79c286_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="journalentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_id", ""), _negated=True),
                fields=("source_type", "source_id", "source_key"),
                name="accounting_journal_source_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalline",
            constraint=models.CheckConstraint(
                condition=models.Q(("debit__gte", 0), ("credit__gte", 0)),
                name="accounting_line_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("debit__gt", 0), ("credit", 0)),
                    models.Q(("credit__gt", 0), ("debit", 0)),
                    _connector="OR",
                ),
                name="accounting_line_one_side_only",
            ),
        ),
    ]
