# Generated by Django 6.0.4 on 2026-09-20 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0002_initial"),
        ("sales", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last updated this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="salesinvoice",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="salesinvoice",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="sales.customer",
            ),
        ),
        migrations.AddField(
            model_name="salesinvoice",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last updated this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="salesinvoiceitem",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="sales.salesinvoice",
            ),
        ),
        migrations.AddField(
            model_name="salesinvoiceitem",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales",
                to="inventory.variant",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="sales.customer",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last updated this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="salesinvoice",
            name="order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice",
                to="sales.salesorder",
            ),
        ),
        migrations.AddField(
            model_name="salesorderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="sales.salesorder",
            ),
        ),
        migrations.AddField(
            model_name="salesorderitem",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales_items",
                to="inventory.variant",
            ),
        ),
        migrations.AddField(
            model_name="salespayment",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="sales.customer",
            ),
        ),
        migrations.AddField(
            model_name="salespayment",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="sales.salesinvoice",
            ),
        ),
        migrations.AddField(
            model_name="salespayment",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="sales.salesorder",
            ),
        ),
        migrations.AddField(
            model_name="salespayment",
            name="processed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["code"], name="sales_custo_code_4ece8f_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["email"], name="sales_custo_email_b3bee2_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["phone"], name="sales_custo_phone_43e3c6_idx"),
        ),
        migrations.AddIndex(
            model_name="salesinvoiceitem",
            index=models.Index(
                fields=["invoice"], name="sales_sales_invoice_a93c56_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesinvoiceitem",
            index=models.Index(
                fields=["variant"], name="sales_sales_variant_30f5ca_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="salesinvoiceitem",
            constraint=models.UniqueConstraint(
                fields=("invoice", "variant"), name="unique_sales_invoice_variant"
            ),
        ),
        migrations.AddIndex(
            model_name="salesorder",
            index=models.Index(fields=["code"], name="sales_sales_code_17843b_idx"),
        ),
        migrations.AddIndex(
            model_name="salesorder",
            index=models.Index(fields=["status"], name="sales_sales_status_480214_idx"),
        ),
        migrations.AddIndex(
            model_name="salesorder",
            index=models.Index(
                fields=["customer", "order_date"], name="sales_sales_custome_23226b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesinvoice",
            index=models.Index(fields=["code"], name="sales_sales_code_1bbfb6_idx"),
        ),
        migrations.AddIndex(
            model_name="salesinvoice",
            index=models.Index(fields=["status"], name="sales_sales_status_826768_idx"),
        ),
        migrations.AddIndex(
            model_name="salesinvoice",
            index=models.Index(
                fields=["customer"], name="sales_sales_custome_5940c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesorderitem",
            index=models.Index(fields=["order"], name="sales_sales_order_i_cbcfda_idx"),
        ),
        migrations.AddIndex(
            model_name="salesorderitem",
            index=models.Index(
                fields=["variant"], name="sales_sales_variant_b6bf03_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="salesorderitem",
            constraint=models.UniqueConstraint(
                fields=("order", "variant"), name="unique_sales_order_variant"
            ),
        ),
        migrations.AddIndex(
            model_name="salespayment",
            index=models.Index(
                fields=["payment_id"], name="sales_sales_payment_ab342a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salespayment",
            index=models.Index(
                fields=["transaction_id"], name="sales_sales_transac_813a8f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salespayment",
            index=models.Index(
                fields=["status", "payment_date"], name="sales_sales_status_80d802_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salespayment",
            index=models.Index(
                fields=["invoice", "status"], name="sales_sales_invoice_29fd4e_idx"
            ),
        ),
    ]
